# Generated by Django 4.0.1 on 2022-01-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_intake_end_date_intake_start_daet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intake',
            old_name='start_daet',
            new_name='start_date',
        ),
    ]
